# Default config.yml for Engine
spells:
  explosion:
    description: Launches a projectile that causes a large explosion.
    class: com.gmail.spraetz.spells.Explosion
    reagents:
      - reagent: FLINT
        quantity: 1
      - reagent: WHEAT
        quantity: 1
    settings:
      radius: 3
      damage_multiplier: 1
  fire_ball:
    description: Launches a projectile that ignites nearby things.
    class: com.gmail.spraetz.spells.FireBall
    reagents:
      - reagent: FLINT
        quantity: 1
      - reagent: CACTUS
        quantity: 1
    settings:
      radius: 1
      damage_multiplier: 1
      ignite_radius: 3
      fire_ticks: 100
  lightning_bolt:
    description: Causes a bolt of lightning to strike where targeted.
    class: com.gmail.spraetz.spells.LightningBolt
    reagents:
      - reagent: COAL
        quantity: 1
      - reagent: WHEAT
        quantity: 1
  teleport:
    description: Teleports the player to the targeted location.
    class: com.gmail.spraetz.spells.Teleport
    reagents:
      - reagent: EGG
        quantity: 1
      - reagent: LEATHER
        quantity: 1
  stone_wall:
    description: Creates a temporary wall made of bedrock where targeted.
    class: com.gmail.spraetz.spells.Wall
    reagents:
      - reagent: WHEAT
        quantity: 2
    settings:
      material: BEDROCK
      height: 5
      width: 4
      minimum_ticks: 80
      maximum_ticks: 120
  heal_self:
    description: Restores your own hearts.
    class: com.gmail.spraetz.spells.HealSelf
    reagents:
      - reagent: WOOL
        quantity: 1
      - reagent: FEATHER
        quantity: 1
    settings:
      percent_of_max_health: 30
  heal_other:
    description: Restores the health of the entity you click.  Must be close enough to touch.
    class: com.gmail.spraetz.spells.HealOther
    reagents:
      - reagent: WOOL
        quantity: 1
      - reagent: SUGAR_CANE
        quantity: 1
    settings:
      percent_of_max_health: 30
  recall:
    description: Takes the player back to their bed spawn or server spawn if there is none.
    class: com.gmail.spraetz.spells.Recall
    reagents:
      - reagent: EGG
        quantity: 1
      - reagent: WOOL
        quantity: 1
  flight:
    description: Grants the player the ability to fly temporarily.
    class: com.gmail.spraetz.spells.Flight
    reagents:
      - reagent: FEATHER
        quantity: 1
      - reagent: LEATHER
        quantity: 1
    settings:
      ticks: 400
  push:
    description: Knocks an entity way back.  Must be close enough to touch.
    class: com.gmail.spraetz.spells.Push
    reagents:
      - reagent: WHEAT
        quantity: 2
    settings:
      knockback: 2.0
      up_force: 0.5
      max_up_force: 1.0
  ignite:
    description: Sets an entity on fire.  Must be close enough to touch.
    class: com.gmail.spraetz.spells.Ignite
    reagents:
      - reagent: COAL
        quantity: 2
    settings:
      ticks: 150
  poison:
    description: Poisons an entity.  Must be close enough to touch.
    class: com.gmail.spraetz.spells.Poison
    reagents:
      - reagent: NETHER_STALK
        quantity: 2
    settings:
      ticks: 300
      amplifier: 1
  restore:
    description: Removes all negative effects from yourself.
    class: com.gmail.spraetz.spells.Restore
    reagents:
      -  reagent: WHEAT
         quantity: 1
      -  reagent: WOOL
         quantity: 1

allow_tracking: true
auto_update: true
guid: null